// ===== Esencja Pet Care — katalog produktów =====
const PRODUCTS = [
  {
    id: "paw-nose-balm",
    name: "Paw & Nose Natural Balm",
    namePl: "Naturalny balsam do łap i nosa",
    category: "pielegnacja",
    price: 45.00,
    volume: "50 ml",
    badge: "Bestseller",
    badgeClass: "",
    img: "assets/img/paw-nose-balm.png",
    short: "Naturalny balsam do suchych i popękanych opuszek łap oraz nosa. Bezzapachowy, bezpieczny przy zlizywaniu.",
    long: "Naturalny balsam stworzony, aby pielęgnować suche i popękane opuszki łap oraz nosy. Wykonany w całości z naturalnych składników, zapewnia długotrwałą pielęgnację i odżywienie. Bezzapachowy i bezpieczny przy ewentualnym zlizywaniu — idealny dla wrażliwych zwierząt domowych.",
    attrs: ["100% naturalne składniki", "Bezpieczny przy zlizywaniu", "Bezzapachowy", "Dla psów i kotów"],
    ingredients: "INCI: Vitis Vinifera Seed Oil, Caprylic/Capric Triglyceride, Olea Europaea Fruit Oil, Glycerin, Helianthus Annuus Seed Oil, Aqua, Propolis Cera Extract, Quillaja Saponaria Wood Extract, Tocopherol, Saponaria Officinalis (Soapwort) Leaf/Root Extract. Składniki: olej z nasion winorośli właściwej, trójglicerydy kaprylowo-kaprynowe, olej z owoców oliwki europejskiej, gliceryna, olej z nasion słonecznika, woda, ekstrakt z propolisu, ekstrakt z mydłodrzewu, tokoferol, ekstrakt z mydlnicy lekarskiej.",
    usage: "Wetrzeć niewielką ilość w opuszki łap lub nos pupila codziennie, aby utrzymać je miękkie i gładkie. Odpowiedni również do pielęgnacji suchych i szorstkich miejsc, takich jak łokcie psów. Tylko do użytku zewnętrznego. Przechowywać w miejscu niedostępnym dla dzieci."
  },
  {
    id: "dental-spray",
    name: "Dental Spray",
    namePl: "Spray do higieny jamy ustnej",
    category: "higiena",
    price: 41.00,
    volume: "100 ml",
    badge: "Nowość",
    badgeClass: "blue",
    img: "assets/img/dental-spray.png",
    short: "Erytrytol i inulina chronią mikrobiom jamy ustnej, ograniczają osad i dają świeży oddech.",
    long: "Formuła opracowana wyłącznie z użyciem składników pochodzenia naturalnego. Zawiera erytrytol oraz inulinę, które chronią mikrobiom jamy ustnej i ograniczają powstawanie osadu nazębnego oraz zapewniają świeży oddech zwierzęcia. Bez stresującego szczotkowania.",
    attrs: ["Składniki pochodzenia naturalnego", "Produkt wegański", "Dla psów i kotów w każdym wieku", "Bez szczotkowania"],
    ingredients: "INCI: Aqua, Fructooligosaccharides, Erythritol, Inulin, Glycerin, Sodium Gluconate, p-Anisic Acid, Polyglycerin-10, Polylysine, Coco-Glucoside, Arginine, Aroma. Składniki: woda, fruktooligosacharydy, erytrytol, inulina, gliceryna, glukonian sodu, kwas p-anyżowy, poligliceryna-10, polilizyna, glukozyd kokosowy, arginina, aromat.",
    usage: "Spryskać bezpośrednio obie strony jamy ustnej zwierzęcia. Produkt do codziennego stosowania, odpowiedni dla psów i kotów w każdym wieku, niezależnie od rasy i wielkości. Dla uzyskania najlepszych efektów stosować regularnie jako element codziennej pielęgnacji."
  },
  {
    id: "anti-odour-shampoo",
    name: "Anti Odour Pet Shampoo",
    namePl: "Naturalny szampon neutralizujący zapachy",
    category: "kapiel",
    price: 37.00,
    volume: "250 ml",
    badge: "Ulubieniec",
    badgeClass: "green",
    img: "assets/img/anti-odour-shampoo.png",
    short: "Rycynoleinian cynku pochłania nawet najtrudniejsze zapachy. Zrównoważone pH, delikatne mycie.",
    long: "Naturalny szampon o zrównoważonym pH, przeznaczony do neutralizacji nawet najtrudniejszych zapachów, pozostawiający sierść świeżą i czystą. Formuła oparta na naturalnym rycynoleinianie cynku skutecznie pochłania nieprzyjemne zapachy, a łagodne składniki myjące zapewniają delikatne oczyszczanie bez podrażnień.",
    attrs: ["Zrównoważone pH", "Produkt wegański", "Kompozycja zapachowa wolna od alergenów", "Składniki pochodzenia naturalnego"],
    ingredients: "INCI: Aqua, Sodium Olivoyl Glutamate, Disodium Cocoyl Glutamate, Lauryl Glucoside, Cellulose Gum, Zinc Ricinoleate, Tetrasodium Glutamate Diacetate, Sodium Gluconate, Propanediol, Caprylyl Glycol, Caprylhydroxamic Acid, Glycerin, Parfum, Ethyl Lauroyl Arginate HCl, Citric Acid. Składniki: woda, oliwoiloglutaminian sodu, kokoiloglutaminian disodowy, glukozyd laurylowy, guma celulozowa, rycynoleinian cynku, dioctan glutaminianu tetrasodowego, glukonian sodu, propanodiol, glikol kaprylowy, kwas kaprylohydroksamowy, gliceryna, kompozycja zapachowa, chlorowodorek estru etylowego lauroiloargininy, kwas cytrynowy.",
    usage: "Delikatnie wmasować w mokrą sierść. Dokładnie spłukać i w razie potrzeby powtórzyć czynność. Produkt odpowiedni do częstego stosowania."
  },
  {
    id: "puppy-shampoo",
    name: "Puppy Shampoo Extra Sensitive",
    namePl: "Szampon dla szczeniąt — bardzo delikatny",
    category: "kapiel",
    price: 49.00,
    volume: "250 ml",
    badge: "Dla szczeniąt",
    badgeClass: "green",
    img: "assets/img/puppy-shampoo.png",
    short: "Łagodny szampon o zbalansowanym pH na pierwsze kąpiele. Bezzapachowy, wolny od alergenów.",
    long: "Łagodny szampon o zbalansowanym pH, stworzony z naturalnych i wegańskich składników, aby delikatnie oczyszczać sierść oraz skórę szczenięcia, dbając o jej naturalną barierę ochronną. Wzbogacony kojącą mieszanką ekstraktów z ziarna owsa i nagietka, które łagodzą podrażnienia. Produkt bezzapachowy, wolny od alergenów zapachowych, zapewniający czystą i bezpieczną pielęgnację.",
    attrs: ["Extra Sensitive", "Zrównoważone pH", "Produkt wegański", "Bezzapachowy"],
    ingredients: "INCI: Aqua, Disodium cocoyl glutamate, Sodium olivoyl glutamate, Glycerin, Cellulose gum, Lauryl glucoside, Sodium chloride, Sodium gluconate, Caprylyl Glycol, Glyceryl caprylate, Dipropylene glycol, Ethyl Lauroyl Arginate HCl, Calendula officinalis Flower Extract, Avena sativa (Oat) Kernel Extract, Sodium benzoate, Potassium sorbate, Citric acid.",
    usage: "Delikatnie wmasować w mokrą sierść. Spłukać i w razie potrzeby powtórzyć czynność. Odpowiedni do częstego stosowania."
  },
  {
    id: "paw-cleaning-foam",
    name: "Paw Cleaning Foam",
    namePl: "Pianka do pielęgnacji łap",
    category: "pielegnacja",
    price: 44.00,
    volume: "200 ml",
    badge: "Po spacerze",
    badgeClass: "",
    img: "assets/img/paw-cleaning-foam.png",
    short: "Łagodna pianka do mycia łap bez spłukiwania — z silikonową szczoteczką w zestawie.",
    long: "Łagodna pianka do mycia łap psa bez spłukiwania, stworzona na bazie składników pochodzenia naturalnego. Puszysta formuła w połączeniu z miękką silikonową szczoteczką pozwala na precyzyjne i skuteczne oczyszczenie trudno dostępnych miejsc, nie naruszając przy tym naturalnej bariery ochronnej i lipidowej łap Twojego psa.",
    attrs: ["Składniki pochodzenia naturalnego", "Produkt wegański", "Nietestowane na zwierzętach", "Bez spłukiwania"],
    ingredients: "INCI: Aqua, Sodium Olivoyl Glutamate, Disodium Cocoyl Glutamate, Betaine, Sodium Gluconate, Lactobacillus ferment, Citric Acid, Propanediol, Caprylyl Glycol, Caprylhydroxamic Acid.",
    usage: "Zdejmij nasadkę i naciśnij pompkę, aby nanieść piankę na miękkie silikonowe wypustki załączonej szczoteczki. Delikatnie wmasuj piankę w łapy psa oraz przestrzenie między opuszkami, wykonując okrężne ruchy. Wytrzyj do sucha — produkt nie wymaga spłukiwania. Stosuj po każdym spacerze lub w zależności od potrzeb. Po użyciu zdejmij osłonkę szczoteczki i wypłucz wypustki pod ciepłą wodą."
  },

  // ===== ZESTAWY =====
  {
    id: "zestaw-spacerowicz",
    name: "Zestaw Spacerowicz",
    namePl: "Pianka do łap + Balsam do łap i nosa",
    category: "zestawy",
    price: 83.90,
    oldPrice: 89.00,
    volume: "200 ml + 50 ml",
    badge: "Zestaw −6%",
    badgeClass: "",
    img: "assets/img/zestaw-spacerowicz.png",
    short: "Duet na każdy spacer: pianka czyści łapy bez kąpieli, balsam regeneruje i chroni opuszki.",
    long: "Kompletna pielęgnacja łap w jednym zestawie. Po spacerze pianka z silikonową szczoteczką błyskawicznie usuwa błoto, kurz i sól drogową, a naturalny balsam regeneruje i natłuszcza opuszki oraz nos. Idealny duet na jesień i zimę — a przy okazji taniej niż osobno.",
    attrs: ["Paw Cleaning Foam 200 ml", "Paw & Nose Balm 50 ml", "Oszczędzasz 5,10 zł"],
    ingredients: "W zestawie: Paw Cleaning Foam (200 ml) oraz Paw & Nose Natural Balm (50 ml). Pełne składy znajdziesz na stronach produktów.",
    usage: "Po spacerze umyj łapy pianką i wytrzyj do sucha, następnie wmasuj niewielką ilość balsamu w opuszki. Balsam stosuj również na nos w razie potrzeby."
  },
  {
    id: "zestaw-pierwsze-kapiele",
    name: "Zestaw Pierwsze Kąpiele",
    namePl: "Szampon dla szczeniąt + Balsam do łap i nosa",
    category: "zestawy",
    price: 88.90,
    oldPrice: 94.00,
    volume: "250 ml + 50 ml",
    badge: "Dla szczeniąt",
    badgeClass: "green",
    img: "assets/img/zestaw-pierwsze-kapiele.png",
    short: "Wyprawka pielęgnacyjna dla szczeniaka: ekstradelikatny szampon i bezpieczny balsam do łapek.",
    long: "Wszystko, czego potrzebuje szczeniak na start. Bezzapachowy szampon Extra Sensitive o zbalansowanym pH delikatnie myje wrażliwą skórę malucha, a naturalny balsam dba o miękkie łapki przyzwyczajające się do pierwszych spacerów. Bezpieczny przy zlizywaniu.",
    attrs: ["Puppy Shampoo 250 ml", "Paw & Nose Balm 50 ml", "Oszczędzasz 5,10 zł"],
    ingredients: "W zestawie: Puppy Shampoo Extra Sensitive (250 ml) oraz Paw & Nose Natural Balm (50 ml). Pełne składy znajdziesz na stronach produktów.",
    usage: "Szampon: delikatnie wmasować w mokrą sierść i spłukać. Balsam: wcierać w opuszki łap po spacerach."
  },
  {
    id: "zestaw-swiezosc",
    name: "Zestaw Świeżość",
    namePl: "Dental Spray + Szampon Anti Odour",
    category: "zestawy",
    price: 73.90,
    oldPrice: 78.00,
    badge: "Zestaw −5%",
    badgeClass: "blue",
    volume: "100 ml + 250 ml",
    img: "assets/img/zestaw-swiezosc.png",
    short: "Świeży oddech i świeża sierść — duet przeciw wszystkim psim zapachom.",
    long: "Połączenie, które docenią wszyscy domownicy. Dental Spray z erytrytolem i inuliną dba o świeży oddech i ogranicza osad nazębny, a szampon Anti Odour z rycynoleinianem cynku pochłania nieprzyjemne zapachy sierści zamiast je maskować.",
    attrs: ["Dental Spray 100 ml", "Anti Odour Shampoo 250 ml", "Oszczędzasz 4,10 zł"],
    ingredients: "W zestawie: Dental Spray (100 ml) oraz Anti Odour Pet Shampoo (250 ml). Pełne składy znajdziesz na stronach produktów.",
    usage: "Spray: psikać codziennie na obie strony jamy ustnej. Szampon: stosować podczas kąpieli w razie potrzeby."
  },
  {
    id: "zestaw-czysty-pies",
    name: "Zestaw Czysty Pies",
    namePl: "Pianka do łap + Szampon Anti Odour",
    category: "zestawy",
    price: 75.90,
    oldPrice: 81.00,
    volume: "200 ml + 250 ml",
    badge: "Zestaw −6%",
    badgeClass: "green",
    img: "assets/img/zestaw-czysty-pies.png",
    short: "Czystość na co dzień: łapy po każdym spacerze, pełna kąpiel gdy trzeba.",
    long: "Praktyczny zestaw do utrzymania czystości na co dzień. Pianka do łap załatwia szybkie czyszczenie po spacerze bez kąpieli, a gdy przychodzi czas na pełne mycie — szampon Anti Odour neutralizuje zapachy i pozostawia sierść świeżą i czystą.",
    attrs: ["Paw Cleaning Foam 200 ml", "Anti Odour Shampoo 250 ml", "Oszczędzasz 5,10 zł"],
    ingredients: "W zestawie: Paw Cleaning Foam (200 ml) oraz Anti Odour Pet Shampoo (250 ml). Pełne składy znajdziesz na stronach produktów.",
    usage: "Pianka: po każdym spacerze, bez spłukiwania. Szampon: podczas kąpieli, dokładnie spłukać."
  },
  {
    id: "zestaw-pelna-esencja",
    name: "Zestaw Pełna Esencja",
    namePl: "Wszystkie 5 produktów — kompletna pielęgnacja",
    category: "zestawy",
    price: 194.90,
    oldPrice: 216.00,
    volume: "5 produktów",
    badge: "Mega zestaw −10%",
    badgeClass: "",
    img: "assets/img/zestaw-pelna-esencja.png",
    short: "Cała linia Esencja Pet Care w jednym pudełku — od łap po świeży oddech. Oszczędzasz ponad 21 zł.",
    long: "Kompletna pielęgnacja od nosa po ogon: balsam do łap i nosa, pianka do czyszczenia łap z silikonową szczoteczką, szampon Anti Odour, ekstradelikatny szampon dla szczeniąt oraz Dental Spray. Idealny na start, na prezent dla psiego rodzica — albo po prostu dlatego, że Twój pies zasługuje na wszystko.",
    attrs: ["Paw & Nose Balm 50 ml", "Paw Cleaning Foam 200 ml", "Anti Odour Shampoo 250 ml", "Puppy Shampoo 250 ml", "Dental Spray 100 ml", "Oszczędzasz 21,10 zł"],
    ingredients: "W zestawie wszystkie 5 produktów Esencja Pet Care. Pełne składy znajdziesz na stronach poszczególnych produktów.",
    usage: "Każdy produkt stosuj zgodnie z instrukcją na opakowaniu. Zestaw przyjeżdża w jednym pudełku — gotowy również na prezent."
  }
];

const FREE_SHIPPING_FROM = 149; // zł
const SHIPPING_COST = 14.99;    // zł
